### ISSUE TITLE
Question on uploading to cloudinary

### ISSUE THREAD

**Issue by erichodges** [cloudinary-devs/gatsby-transformer-cloudinary#10]
I'm wondering what the advantage of uploading local images to cloudinary is. One could upload images directly to a folder on cloudinary and then they would not be needed in the project repo.

**Comment by jlengstorf** [comment]
@erichodges primarily: convenience. This consolidates your workflow to just the repo, and if you're working with multiple developers it can put everything in one place via CI instead of sharing Cloudinary credentials all over (which would be a nightmare for e.g. an OSS project).

If this isn't your situation and you want to use Cloudinary with Gatsby without uploading local files, you can also use the [manual approach](https://gatsby-transformer-cloudinary.netlify.com/manual/).

Hope this helps! I'm going to close, but feel free to follow up if you have additional questions.
