### ISSUE TITLE
Improve error logging 

### ISSUE THREAD

**Issue by mduecker** [cloudinary-devs/gatsby-transformer-cloudinary#4]
Could we add more detail to the error messages (during build)?
If this is something that can be done within the plugin, I'm happy to work on a PR for this.

> Errors:
>   Request failed with status code 404
> 
>   GraphQL request:8:13
>   7 |           childImageSharp: childCloudinaryAsset {
>   8 |             fluid {
>     |             ^
>   9 |               ...CloudinaryAssetFluid,Request failed with status code 404

**Comment by jlengstorf** [comment]
Yeah, we should be able to catch errors from Cloudinary's SDK and axios requests to output more helpful errors. Let me know if you have any questions as you dive in! Looking forward to your PRs. Thanks for being willing to help!

**Comment by masives** [comment]
Hi, I also faced such issue.
![image](https://user-images.githubusercontent.com/18038829/67837317-151f2080-faef-11e9-9d5a-f375345a4d16.png)

However printing node for the issue helps with debugging as it turned out the file that plugin was trying to transform was incomplete. @jlengstorf please tell me if you feel this is sensible and I'd add reported info with the node that has problem.

**Comment by Chuloo** [comment]
Added a try/catch to the Cloudinary uploader so errors from uploads are logged. The rest of the errors I believe are handled by Gatsby. Also, @masives, the errors with uploading multiple images are fixed in #21. With the breakpoints, you can specify custom min and max breakpoints in the `gatsby-config.js` options for the plugin.

@mduecker kindly re-open this issue and suggest any other error logging enhancements if any and we'll be sure to put them in. Closing this for now :)
