### ISSUE TITLE
Turn Off Uploading During Development?

### ISSUE THREAD

**Issue by jasonbiondo** [cloudinary-devs/gatsby-transformer-cloudinary#54]
Is it possible to turn off the uploading of the thousands of files I have during development? This takes several minutes for images that are already on my cloudinary even with overwriteExisting set to false.  Is there a reason why this isn't already in place?  I think it would be nice to toggle that off.

**Comment by Chuloo** [comment]
I think this makes sense, been giving it a thought @kurttomlinson got ideas?

**Comment by kurttomlinson** [comment]
I'd recommend taking a look at the [Use images already on Cloudinary](https://github.com/cloudinary-devs/gatsby-transformer-cloudinary/tree/master/packages/gatsby-transformer-cloudinary#use-images-already-on-cloudinary) section of the documentation. If you use that section, then no images will be uploaded to Cloudinary. The only time Cloudinary will be used is to download base64 images for each image that is part of a GraphQL query. I'm working on a PR right now that will add a way to eliminate that API call as well.

Turning off uploading during development for local images won't really work since the plugin needs some data that comes from the result of the upload API call in order to build out the GraphQL query responses. I'm sure we could get it to work with a lot of effort, but it would be complicated and a much poorer solution than having your data source keep track of the files you've already uploaded and their metadata.

If we added a way to turn uploading on and off, we'd have to also find a way to store the metadata for an image outside of the Gatsby cache. I think that's a responsibility of a data source, not a transformer plugin, so I'm not sure that's something we should implement in this plugin.

**Comment by jasonbiondo** [comment]
@kurttomlinson It seems like it would make sense to cache the meta data outside of gatsby cache.  That would work and would be helpful to spin things up more easily.  I'm not sure how the use images already on cloudinary section applied.  I'm using the shopify plugin for gatsby and all of my product photos get uploaded everytime.  By default, I have no control over the nodes the plugin creates but I would love to have the cloudinary image nodes tied to my product nodes under the allShopifyProducts graphql node.  Is that possible?

**Comment by kurttomlinson** [comment]
@jasonbiondo take a look at https://github.com/DavidWells/cache-me-outside

**Comment by Chuloo** [comment]
Closing this out, we can keep track of the conversation on merging nodes in #34.
